server:
  port: 4040
  servlet:
    contextPath: /cartella-asl

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/aslv2?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}
    username: ${DATASOURCE_USERNAME:asl}
    password: ${DATASOURCE_PASSWORD:asl}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /home/dev/tmp

storage:
  type: localStorage
  local:
    dir: /home/dev/tmp

import:
  dir:  /home/dev/tmp/dataset
export:
  dir: /home/dev/tmp/dataset/aslExport

cartella:
  api: http://localhost:6010/cs-engine

infoTN:
  api: ${INFOTN_API:https://webservices-test.infotn.it/RegistroEsterni}
  startingYear: ${INFOTN_STARTINGYEAR:2017}
  user: ${INFOTN_USER:}
  pass: ${INFOTN_PASS:}
  esAlignUri: ${INFOTN_ESALIGNURI:https://saa-test11.infotn.it/rest/asl/importa}
  esAlignToken: ${INFOTN_ESALIGNTOKEN:}
  esAlignOrigine: ${INFOTN_ESALIGNORIGINE:}

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: 
        client-id: 
      opaque-token:
        introspection-uri: ${AAC_INTROSPECTION_URI:https://aac-adc.platform.smartcommunitylab.it/oauth/introspect}
        client-id: ${AAC_CLIENT_ID:}
        client-secret: ${AAC_CLIENT_SECRET:}

parix:
  endpoint: ${PARIX_ENDPOINT:}
  user: ${PARIX_USER:}
  password: ${PARIX_PASSWORD:}
  keystore:
    uri: ${PARIX_KEYSTORE_FILE:}
    password: ${PARIX_KEYSTORE_PASSWORD:}

mail:
  host: ${MAIL_HOST:}
  port: ${MAIL_PORT:}
  user: ${MAIL_USER:}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:}
  url: ${MAIL_URL:}

management:
  security:
    enabled: false
  port: 4041
  context-path: /manage
